### ISSUE TITLE
Separate Users ( Frontend ) and Admin (Filament Users ) 

### ISSUE THREAD

**Issue by Sebastiangperez** [Log1x/filament-starter#47]
It will be nice if you can separate users from the frontend and admin users for the backend. 
I know that this can be done in Filament with a custom user guard.

**Comment by Log1x** [comment]
Hey, thanks for the suggestion!

I considered doing a simple `is_admin` boolean on the User model along with a condition on [`canAccessPanel`](https://github.com/Log1x/filament-starter/blob/main/app/Models/User.php#L47-L53) but I didn't want to complicate things much past that.

I feel like how users (and permissions) are handled can vary greatly project to project so I opted out of the above as I kind of wanted to keep it open-ended, but I'm not against a simple implementation like that.

Otherwise, there are plugins such as [Filament Shield](https://github.com/bezhanSalleh/filament-shield) that offer fine-grained control of [spatie/laravel-permission](https://github.com/spatie/laravel-permission) and should be pretty straight forward to add to the starter on a per-project basis.

If you want an entirely separate table for (non-Filament) users, I'm afraid that'd be outside the scope of this project.

**Comment by Sebastiangperez** [comment]
Ok, that was some thing that i always did , separate users and admins , for security reasons mostly , maybe you can have admins in another table or another mysql instances and users in another one. 
I like your approach and i will test it.

**Comment by Log1x** [comment]
Hope things are working out! Going to go ahead and close this for now but will keep a simple toggle for admins in mind for the future possibly.
