### ISSUE TITLE
Remove lock files

### ISSUE THREAD

**Issue by madalinignisca** [Log1x/filament-starter#49]
As this is a project template, it must not have composer.lock and yarn.lock files.

**Comment by Log1x** [comment]
Hi!

I agree with you, but in this scenario, I opted to intentionally commit them:

- I don't want to add them to `.gitignore` as they should otherwise be committed in your own project.
- I don't want to dance around them when updating this repo with them not being ignored.
- I like to check that everything is working as intended each time I bump dependencies for this repo.
- Dependabot wouldn't work.

Hopefully this makes sense.

**Comment by Log1x** [comment]
Went ahead and removed them for now.
