### ISSUE TITLE
Change navigation icon and group for filament-exceptions and filament-logger

### ISSUE THREAD

**Issue by LeftPinkie** [Log1x/filament-starter#59]
How to I change the panel navigation icon and group name for `filament-exceptions` and `filament-logger`?

**Comment by Log1x** [comment]
For Logger, you can set the navigationLabel on the extended [ActivityResource class](https://github.com/Log1x/filament-starter/blob/main/app/Filament/Resources/ActivityResource.php) similar to other Filament resources.

For Exceptions, if you want full control, you should be able something similar to extending the [ExceptionResource](https://github.com/bezhanSalleh/filament-exceptions/blob/main/src/Resources/ExceptionResource.php) and then removing the plugin from AdminPanelProvider since all it does is [register it's built-in resource](https://github.com/bezhanSalleh/filament-exceptions/blob/main/src/FilamentExceptionsPlugin.php).

Another option is to dump the Exception plugin's locale files and changing it in `filament-exceptions::filament-exceptions.labels.navigation`.

**Comment by LeftPinkie** [comment]
> For Logger, you can set the navigationLabel on the extended [ActivityResource class](https://github.com/Log1x/filament-starter/blob/main/app/Filament/Resources/ActivityResource.php) similar to other Filament resources.

For `filament-logger`, I have tried setting in `app/Filament/Resources/ActivityResource.php`:
```
protected static ?string $navigationGroup = 'SYSTEM';
````
and does not work. Also trying to figure out where the icon is set so that I can change.

**Comment by Log1x** [comment]
Hmm, that should work. The icon can be set the same, https://github.com/Z3d0X/filament-logger/blob/main/src/Resources/ActivityResource.php#L29-L32

**Comment by Log1x** [comment]
Oh nevermind, I see, they override the method. You'll have to use that instead of the property or return the property inside of  it.

https://github.com/Z3d0X/filament-logger/blob/main/src/Resources/ActivityResource.php#L325-L333
