### ISSUE TITLE
The POST method is not supported for route admin/login. Supported methods: GET, HEAD.

### ISSUE THREAD

**Issue by KecajGr** [Log1x/filament-starter#62]
Hello

When transferring to hosing, the following message appears when logging in:

The POST method is not supported for route admin/login. Supported methods: GET, HEAD.

applies to the page: https://host238122.xce.pl/filament/public/admin/login

user:admin
pass:123456789

**Comment by KecajGr** [comment]
user:admin
pass:123456789

**Comment by Log1x** [comment]
It sounds like something is preventing Livewire from loading and thus is doing a POST request to the login route instead of firing `wire:submit` - I would check `storage/framework/logs/laravel.log` and see if it has any errors. I know Livewire in particular requires a few functions that are typically disabled by default on some shared hosts - but why this is happening could stem from a lot of different things.

**Comment by krasa** [comment]
Newbie here. Same. I was using xampp firectly by 'http://localhost:80/qqq/filament-starter/public/index.php' instead of `php artisan serve`
